export const data = [
  {
    category: "СҮҮЛД ҮЗСЭН",
    movies: [
      {
        id: 1,
        image: "../images/movie1.webp",
        type: ["ГЭМТ ХЭРЭГ", "УЯНГА"],
        name: ["Гал командын хажуу дахь цагдаагийн газар"],
        year: ["2022"],
      },
      {
        id: 2,
        image: "../images/movie2.webp",
        type: ["АДАЛ ЯВДАЛ", "УЯНГА"],
        name: ["Сул дорой баатар"],
        year: ["2010"],
      },
      {
        id: 3,
        image: "../images/movie3.webp",
        type: ["ГЭМТ ХЭРЭГ", "УЯНГА", "ГЭР БҮЛ"],
        name: ["Хэн нэгэн"],
        year: ["2020"],
      },
      {
        id: 4,
        image: "../images/movie4.webp",
        type: ["ИНЭЭДЭМ", "УЯНГА"],
        name: ["Шүтэн бишрэгчийн захидал илгээж өгөөч"],
        year: ["2020"],
      },
      {
        id: 5,
        image: "../images/movie5.webp",
        type: ["ИНЭЭДЭМ", "ГЭР БҮЛ"],
        name: ["Сүнсийг барь"],
        year: ["2019"],
      },
    ],
  },
  {
    category: "ШИНЭ КИНО",
    movies: [
      {
        id: 6,
        image: "../images/movie6.webp",
        type: ["ИНЭЭДЭМ", "РОМАНТИК"],
        name: ["Дутагдалтай хүмүүс"],
        year: ["2015"],      
      },
      {
        id: 7,
        image: "../images/movie7.webp",
        name: ["Хайр дурлал ч гэх шиг"],
        year: ["2022"],
      },
      {
        id: 8,
        image: "../images/movie8.webp",
        name: ["Жин прокурорын ялалт, ялагдал"],
        year: ["2021"],
      },
      {
        id: 9,
        image: "../images/movie9.webp",
        name: ["Ноёрхол хуулийн гүрэн"],
        year: ["2019"],
      },
      {
        id: 10,
        image: "../images/movie10.webp",
        name: ["Cheer up"],
        year: ["2015"],
      },
      {
        id: 11,
        image: "../images/movie21.webp",
        type: ["УЯНГА", "ГЭР БҮЛ"],
        name: ["Wednesday"],
        year: ["2010"],
      },
      {
        id: 12,
        image: "../images/movie22.webp",
        type: ["ГЭМТ ХЭРЭГ", "УРАН ЗӨГНӨЛ"],
        name: ["Холбоо"],
        year: ["2011"],
      },
      {
        id: 13,
        image: "../images/movie23.webp",
        type: ["УЯНГА"],
        name: ["Юу ч хиймээргүй байна"],
        year: ["2010"],
      },
      {
        id: 14,
        image: "../images/movie24.webp",
        type: ["УРАН ЗӨГНӨЛ","РОМАНТИК","ӨСВӨР НАС"],
        name: ["Муу ёр"],
        year: ["2011"],
      },
      {
        id: 15,
        image: "../images/movie25.webp",
        type: ["ГЭР БҮЛ","ШИНЖЛЭХ УХААН","УЯНГА"],
        name: ["Ёндэр"],
        year: ["2022"],
      },
    ],
  },
  {
    category: "САНАЛ БОЛГОХ",
    movies: [
      {
        id: 16,
        image: "../images/movie11.webp",
        name: ["Pink Lie"],
        year: ["2021"],
      },
      {
        id: 17,
        image: "../images/movie12.webp",
        name: ["Ноёрхол хуулийн гүрэн"],
        year: ["2022"],
      },
      {
        id: 18,
        image: "../images/movie13.webp",
        name: ["1000 воны өмгөөлөгч"],
        year: ["2020"],
      },
      {
        id: 19,
        image: "../images/movie14.webp",
        name: ["Алтан халбага"],
        year: ["2012"],
      },
      {
        id: 20,
        image: "../images/movie15.webp",
        name: ["Өмгөөллөө эхэлье"],
        year: ["2012"],
      },
      {
        id: 21,
        image: "../images/movie26.webp",
        type: ["ИНЭЭДЭМ","ГЭР БҮЛ", "УЯНГА"],
        name: ["Гэнэтийн дохио"],
        year: ["2013"],
      },
      {
        id: 22,
        image: "../images/movie27.webp",
        type: ["ИНЭЭДЭМ","РОМАНТИК"],
        name: ["Гаус Электроникс"],
        year: ["2015"],
      },
      {
        id: 23,
        image: "../images/movie28.webp",
        type: ["ИНЭЭДЭМ","РОМАНТИК"],
        name: ["Дутагдалтай хүмүүс"],
      },
      {
        id: 24,
        image: "../images/movie29.webp",
        type: ["ИНЭЭДЭМ","ГЭМТ ХЭРЭГ"],
        name: ["Сүнсийг барь"],
        year: ["2015"],
      },
      {
        id: 25,
        image: "../images/movie30.webp",
        type: ["ГЭМТ ХЭРЭГ"],
        name: ["Мөрдөгч Руг"],
        year: ["2014"],
      },
    ],
  },
  {
    category: "ОЛОН АНГИТ",
    movies: [
      {
        id: 22,
        image: "../images/movie16.webp",
        name: ["Суринам"],
        year: ["2015"],
      },
      {
        id: 23,
        image: "../images/movie17.webp",
        name: ["Романтик ДНХ"],
        year: ["2017"],
      },
      {
        id: 24,
        image: "../images/movie18.webp",
        name: ["Хуулийн кафе"],
        year: ["2017"],
      },
      {
        id: 25,
        image: "../images/movie19.webp",
        name: ["Сүүлчийн зэвсэг Алис"],
        year: ["2017"],
      },
      {
        id: 26,
        image: "../images/movie20.webp",
        name: ["Өнөөдрийн Вэбтүүн"],
        year: ["2019"],
      },
      {
        id: 27,
        image: "../images/movie31.webp",
        type: ["РОМАНТИК","ЛГБТ+"],
        name: ["Утга зүйн алдаа"],
        year: ["2019"],
      },
      {
        id: 28,
        image: "../images/movie32.webp",
        type: ["ГЭМТ ХЭРЭГ"," УЯНГА"],
        name: ["Гал командын хажуу дахь цагдаагийн газар"],
        year: ["2021"],
      },
      {
        id: 29,
        image: "../images/movie33.webp",
        type: ["НЭВТРҮҮЛЭГ"],
        name: ["Pink Lie"],
        year: ["2018"],
      },
      {
        id: 30,
        image: "../images/movie34.webp",
        type: ["АДАЛ ЯВДАЛ","УЯНГА"],
        name: ["Хоёр Хүсэл /DUB/"],
        year: ["2016"],
      },
      {
        id: 31,
        image: "../images/movie35.webp",
        type: ["ГЭМТ ХЭРЭГ","УЯНГА"],
        name: ["Бусдын өшөө авалт"],
        year: ["2020"],
      },
    ],
  },
  {
    category: "KDRAMA",
    movies: [
      {
        id: 32,
        image: "../images/movie36.webp",
        type: ["ХҮҮХДИЙН","ГЭР БҮЛ"],
        name: ["Bigfoot family"],
        year: ["2020"],
      },
    ]
  }
];
